config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  get 'okinawas/index'
  get 'kyusyus/index'
  get 'sikokus/index'
  get 'tyugokus/index'
  get 'kinkis/index'
  get 'items/search'
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: :show
  resources :kantos, only: :index
  resources :hokkaidos, only: :index
  resources :touhokus, only: :index
  resources :tyubus, only: :index
  resources :kinkis, only: :index
  resources :tyugokus, only: :index
  resources :sikokus, only: :index
  resources :kyusyus, only: :index
  resources :okinawas, only: :index
  resources :users, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :text, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name:  '--お着物の種類を選択してください--' },
    { id: 2, name:  '訪問着' },
    { id: 3, name:  '黒留袖' },
    { id: 4, name:  '色留袖' },
    { id: 5, name:  '付下' },
    { id: 6, name:  '色無地' },
    { id: 7, name:  '小紋' },
    { id: 8, name:  '紬' },
    { id: 9, name:  '浴衣' },
    { id: 10, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/models/item.rb
class Item < ApplicationRecord
  with_options presence: true do
    validates :image
    validates :title
    validates :explanation
    validates :region_id, numericality: { other_than: 1 }
    validates :genre_id, numericality: { other_than: 1 }
  end

    

  belongs_to :user
  has_one_attached :image
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :region
  belongs_to_active_hash :genre
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :item
  belongs_to :user

  validates :text, presence: true
end

app/models/region.rb
class Region < ActiveHash::Base
  self.data = [
    { id: 1, name: '--お住まいの地域を選択してください--' },
    { id: 2, name: '北海道' },
    { id: 3, name: '東北' },
    { id: 4, name: '関東' },
    { id: 5, name: '中部' },
    { id: 6, name: '近畿' },
    { id: 7, name: '中国' },
    { id: 8, name: '四国' },
    { id: 9, name: '九州' },
    { id: 10, name: '沖縄' }
  ]

  include ActiveHash::Associations
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :items
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :item
  def already_liked?(item)
    self.likes.exists?(item_id: item.id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hokkaidos_helper.rb
module HokkaidosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/kantos_helper.rb
module KantosHelper
end

app/helpers/kinkis_helper.rb
module KinkisHelper
end

app/helpers/kyusyus_helper.rb
module KyusyusHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/okinawas_helper.rb
module OkinawasHelper
end

app/helpers/sikokus_helper.rb
module SikokusHelper
end

app/helpers/touhokus_helper.rb
module TouhokusHelper
end

app/helpers/tyubus_helper.rb
module TyubusHelper
end

app/helpers/tyugokus_helper.rb
module TyugokusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">

  <div class="text-white">
    <div class="nav justify-content-center">
      <nav class="navbar navbar-expand-lg navbar-light .bg-primary.bg-gradient">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Copyright(C) -KimonoLovers- All Rights Reserved", "#", class: "nav-link" %>
          </li>
        </ul>
    </div>
  </div>

</footer>

app/views/shared/_header.html.erb
<header class="header">
   
      <nav class="navbar navbar-expand-lg navbar-light .bg-primary.bg-gradient">
        <div class="container-fluid">
          <h2><%= link_to "KimonoLovers", root_path, class:"navbar-brand" %></h2>



        <% if user_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <div class="nav-link active">
            <a> ようこそ、<%= link_to "#{current_user.nickname}", user_path(current_user) %>さん</a>
            </div>
          </li>
          <li>
            <%= link_to "出品する", new_item_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
    <% else %>
        <ul class="navbar-nav">
          <li class="nav-link active"><%= "新規登録orログインはこちらから→" %></li>
          <li class="nav-item">
           <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
        </ul>
    <% end %>
    </div>
</header>

app/views/shared/_kimono.html.erb
<div class="container">
  <div class="row row-cols-4">
    <% @items.each do |item| %>
      <div class="card-deck">
        <div class="card border-white mx-3 mt-3">
          <%= link_to image_tag(item.image, class:"card-img", width:"250", height:"250"), item_path(item.id), method: :get %>
          <div class="card-img-underlay">
            <h4 class="card-title"><%= item.title %></h4>
            <h4 class="card-title">👍<%= item.liked_users.count %></h4>
            <h4 class="card-title">💬<%= item.comments.count %></h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tempretes/_kimono.html.erb
<div class="container">
  <div class="row row-cols-5">
<% @items.each do |item| %>
 <div class="card" style="width: 18rem;">
        <%= link_to image_tag(item.image, class:"bd-placeholder-img card-img-top", width:"200", height:"200"), item_path(item.id), method: :get %>
      <div class="card-body">
        <h5 class="card-title">お名前：<%= item.title %></h5>
        <p class="card-text">地方名：<%= item.region.name %></p>
        <p class="card-text">種類：<%= item.genre.name %></p>
      </div>
  </div>
<% end %>
  </div>
</div>