config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  get 'okinawas/index'
  get 'kyusyus/index'
  get 'sikokus/index'
  get 'tyugokus/index'
  get 'kinkis/index'
  get 'items/search'
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: :show
  resources :kantos, only: :index
  resources :hokkaidos, only: :index
  resources :touhokus, only: :index
  resources :tyubus, only: :index
  resources :kinkis, only: :index
  resources :tyugokus, only: :index
  resources :sikokus, only: :index
  resources :kyusyus, only: :index
  resources :okinawas, only: :index
  resources :users, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :text, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name:  '--お着物の種類を選択してください--' },
    { id: 2, name:  '訪問着' },
    { id: 3, name:  '黒留袖' },
    { id: 4, name:  '色留袖' },
    { id: 5, name:  '付下' },
    { id: 6, name:  '色無地' },
    { id: 7, name:  '小紋' },
    { id: 8, name:  '紬' },
    { id: 9, name:  '浴衣' },
    { id: 10, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items

  end

app/models/item.rb
class Item < ApplicationRecord
  with_options presence: true do
    validates :image
    validates :title
    validates :explanation
    validates :region_id, numericality: { other_than: 1 }
    validates :genre_id, numericality: { other_than: 1 }
  end

    

  belongs_to :user
  has_one_attached :image
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :region
  belongs_to_active_hash :genre
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :item
  belongs_to :user

  validates :text, presence: true
end

app/models/region.rb
class Region < ActiveHash::Base
  self.data = [
    { id: 1, name: '--お住まいの地域を選択してください--' },
    { id: 2, name: '北海道' },
    { id: 3, name: '東北' },
    { id: 4, name: '関東' },
    { id: 5, name: '中部' },
    { id: 6, name: '近畿' },
    { id: 7, name: '中国' },
    { id: 8, name: '四国' },
    { id: 9, name: '九州' },
    { id: 10, name: '沖縄' }
  ]

  include ActiveHash::Associations
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :items
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :item
  def already_liked?(item)
    self.likes.exists?(item_id: item.id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :item_find, only: [:show, :edit, :update, :destroy]
  before_action :search_product, only: [:index, :search]

  def index
    @items = Item.all.order("created_at DESC")
    @all_ranks = Item.find(Like.group(:item_id).order('count(item_id) desc').limit(3).pluck(:item_id))
    set_item_column
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  
  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user).order("created_at DESC")
    @like = Like.new
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id), method: :get
    else
      render 'edit'
    end
  end

  def destroy
    if @item.user.id == current_user.id
      @item.destroy
      redirect_to root_path
    else
      render 'show'
    end
  end

  def search
    @results = @p.result.includes(:user)    
  end

  private

  def item_params
    params.require(:item).permit(:title, :explanation, :region_id, :genre_id, :image).merge(user_id: current_user.id)
  end

  def item_find
    @item = Item.find(params[:id])
  end

  def search_product
    @p = Item.ransack(params[:q])
  end

  def set_item_column
    @item_title = Item.select("title").distinct  # 重複なくnameカラムのデータを取り出す
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hokkaidos_helper.rb
module HokkaidosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/kantos_helper.rb
module KantosHelper
end

app/helpers/kinkis_helper.rb
module KinkisHelper
end

app/helpers/kyusyus_helper.rb
module KyusyusHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/okinawas_helper.rb
module OkinawasHelper
end

app/helpers/sikokus_helper.rb
module SikokusHelper
end

app/helpers/touhokus_helper.rb
module TouhokusHelper
end

app/helpers/tyubus_helper.rb
module TyubusHelper
end

app/helpers/tyugokus_helper.rb
module TyugokusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
 <div class="text-left m-5">
  <%= form_with(model: @item, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <label for="exampleFormControlFile1">お着物の写真を下の「ファイルを選択」ボタンからお選びください</label>
    <h6> </h6>
    <%= f.file_field :image, id:"exampleFormControlFile1" %>
  </div>
  <label for="exampleFormControlInput1">お着物の名前</label>
  <div class="form-group">
    <%= f.text_field :title, class:"form-control", id:"exampleFormControlInput1", placeholder:"例）本場奄美大島で泥染めをした大島紬" %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">地方選択</label>
    <%= f.collection_select(:region_id, Region.all, :id, :name, {}, {class:"form-control"}) %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">種類選択</label>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"form-control"}) %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">説明文</label>
    <%= f.text_area :explanation, class:"form-control", id:"exampleFormControlTextarea1", placeholder:"例）このお着物は、祖母の代から３代にわたって受け継がれてきた振袖です！", rows:"3", maxlength:"1000" %>
  </div>
  <p></p>
    <%= f.submit "出品し直す" ,class:"btn btn-primary btn-lg btn-block" %>
    <%= link_to 'もどる', root_path, class:"btn btn-secondary btn-lg btn-block" %>
  <% end %>
</div>

app/views/items/index.html.erb
<div class="card bg-white text-black border-white">
  <%= image_tag "https://kyoto-kirari.jp/wp-content/uploads/2019/02/ci_01-1.jpg", class:"bd-placeholder-img card-img-top", height:"400" %>
  <div class="card-img-overlay mt-4">
    <div class="top-title">
      <h1>WELCOME</h1>
      <h1>to</h1>
      <h1>KimonoLovers</h1>
    </div>
  </div>
</div>

<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="card bg-white text-black border-white">
        <%= image_tag "https://vasara-h.co.jp/.file/public/2018/12/21/e3a84a42963b6914b20312ee2060a45e/pixta_25013777_M.jpg", class:"bd-placeholder-img card-img-top", height:"600" %>
        <div class="card-img-overlay">
          <h1 class="card-title">KimonoLoversとは？</h1>
          <h4 class="card-text">全国の着物好きな皆さんの交流の場になることを目的としたサービスです。</h4>
          <p class="card-text">近年、着物業界は、「後継者不足」が叫ばれています。</p>
          <p class="card-text">職人さん達の平均年齢はどんどん上がっており、廃業を余儀なくされている方もいらっしゃいます。</p>
          <p class="card-text">しかし、「後継者」とは、必ずしも「作り手」だけではなく、「使い手」もまた後継者の一人です。</p>
          <p class="card-text">日本には今でも職人さん達が命を削って、創作されたお着物が日々、生まれています。</p>
          <p class="card-text">そうしたお着物に恋をした皆様が、思い入れのあるお着物を出品していただくことで、</p>
          <p class="card-text">素敵な作品がより多くの方の目に留まることを願っています。</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class="card bg-white text-white border-white">
        <%= image_tag "https://happy-photo-studio.jp/upload/data/images/7edd0c2f3942e6ece62a25a4af61ed4f1562067958.JPG", class:"bd-placeholder-img card-img-top", width: "800", height:"600" %>
        <div class="card-img-overlay">
          <h2 class="card-text">出品方法は簡単３STEP！</h2>
          <h6 class="card-text">STEP１：右上から「ログイン」、もしくは「新規登録」をしましょう。</h6>
          <h6 class="card-text">STEP２：右上の「出品する」ボタンをクリック！</h6>
          <h6 class="card-text">STEP３：上から順番に入力し、「出品する」ボタンを押して終了です！</h6>
          <h6 class="card-text">出品すると、全国の皆様から、コメントをいただけます！</h6>
          <h4 class="card-text">さあ、いますぐ出品してみませんか？</h4>
        </div>
      </div>
    </div>
   <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only"></span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only"></span>
    </a>
  </div>
</div>



<div class="text-center m-5">
  <h4>INFORMATION</h4>
</div>
<div class="text-center m-4">
  <h6>着物好きな方のための交流サイトをオープンしました。たくさんの方のご参加をお待ちしております！</h6>
</div>

<div class="text-center mt-5">
  <h4><strong>いいねランキング</strong></h4>
</div>
<div class="container">
  <div class="row row-cols-3 mx-5">
    <% @all_ranks.each.with_index(1) do |item, i| %>
      <div class="card-deck">
        <div class="card border-white mt-3">
          <%= link_to image_tag(item.image, class:"card-img", width:"400", height:"400"), item_path(item.id), method: :get %>
          <div class="card-img-underlay">
            <h3 class="card-title">第<%= i %>位</h3>
            <h3 class="card-title mx-4">👍<%= item.liked_users.count %></h3>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%# 日本地図 %>
<div class="text-center mt-5">
<p class="font-weight-bold">
  <h4>地図をクリックして、地方ごとのお着物を見に行きませんか？</h4>
</p>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-auto">
      <nav class="nav flex-column">
       <p class="nav-link active">エリア名</p>
       <p>もっと、日本に逢いに行きましょう</p>
        <a class="nav-link" href="https://kimonolovers.herokuapp.com/hokkaidos">北海道</a>
        <a class="nav-link" href="https://kimonolovers.herokuapp.com/touhokus">東北</a>
        <a class="nav-link" href="https://kimonolovers.herokuapp.com/kantos">関東</a>
        <a class="nav-link" href="https://kimonolovers.herokuapp.com/tyubus">中部</a>
        <a class="nav-link" href="https://kimonolovers.herokuapp.com/kinkis">近畿</a>
        <a class="nav-link" href="https://kimonolovers.herokuapp.com/sikokus">中国</a>
        <a class="nav-link" href="https://kimonolovers.herokuapp.com/sikokus">四国</a>
        <a class="nav-link" href="https://kimonolovers.herokuapp.com/kyusyus">九州</a>
        <a class="nav-link" href="https://kimonolovers.herokuapp.com/okinawas">沖縄</a>
      </nav>
    </div>

    <div class="col">
      <div id="map-container"></div>
    </div>

     <div class="col-md-auto">
      <nav class="nav flex-column">
        <p class="nav-link active">カテゴリー別</p>
        <a class="nav-link" href="http://localhost:3000/hokkaidos">留袖</a>
        <a class="nav-link" href="http://localhost:3000/touhokus">色留袖</a>
        <a class="nav-link" href="http://localhost:3000/kantos">付下</a>
        <a class="nav-link" href="http://localhost:3000/tyubus">色無地</a>
        <a class="nav-link" href="http://localhost:3000/kinkis">小紋</a>
        <a class="nav-link" href="http://localhost:3000/sikokus">紬</a>
        <a class="nav-link" href="http://localhost:3000/sikokus">浴衣</a>
        <a class="nav-link" href="http://localhost:3000/kyusyus">その他</a>
      </nav>
    </div>

   
  </div>
</div>
<%# /日本地図 %>

<%# 着物一覧 %>
<div class="top-item">
<div class="text-center pt-5">
<h4>NEW ARRIVAL</h4>
<%= search_form_for @p, url: items_search_path do |f| %>
  <%= f.label :title_eq, 'タイトル検索' %>
  <%= f.collection_select :title_eq, @item_title, :title, :title,  include_blank: '選択してください' %>
  <%= f.submit '検索' %>
<% end %>
</div>
<%= render "shared/kimono" %>
</div>
<%# /着物一覧 %>

app/views/items/new.html.erb
 <div class="text-left m-5">
  <%= form_with(model: @item, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <label for="exampleFormControlFile1">お着物の写真を下の「ファイルを選択」ボタンからお選びください</label>
    <h6> </h6>
    <%= f.file_field :image, id:"exampleFormControlFile1" %>
  </div>
  <label for="exampleFormControlInput1">お着物の名前</label>
  <div class="form-group">
    <%= f.text_field :title, class:"form-control", id:"exampleFormControlInput1", placeholder:"例）本場奄美大島で泥染めをした大島紬" %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">地方選択</label>
    <%= f.collection_select(:region_id, Region.all, :id, :name, {}, {class:"form-control"}) %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">種類選択</label>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"form-control"}) %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">説明文</label>
    <%= f.text_area :explanation, class:"form-control", id:"exampleFormControlTextarea1", placeholder:"例）このお着物は、祖母の代から３代にわたって受け継がれてきた振袖です！", rows:"3", maxlength:"1000" %>
  </div>
  <p></p>
    <%= f.submit "出品する" ,class:"btn btn-primary btn-lg btn-block" %>
    <%= link_to 'もどる', root_path, class:"btn btn-secondary btn-lg btn-block" %>
  <% end %>
</div>

app/views/items/search.html.erb
<div class="text-center">
<h1>検索結果</h1>
</div>
<%# 検索結果の個数で条件分岐 %>
<% if @results.length !=0 %>
 
  <div class="container">
  <div class="row row-cols-4">
     <% @results.each do |result| %>
      <div class="card-deck">
        <div class="card border-white mx-3 mt-3">
          <%= link_to image_tag(result.image, class:"card-img", width:"250", height:"250"), item_path(result.id), method: :get %>
          <div class="card-img-underlay">
            <h4 class="card-title"><%= result.title %></h4>
            <h4 class="card-title">👍<%= result.liked_users.count %></h4>
            <h4 class="card-title">💬<%= result.comments.count %></h4>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% else %>
  該当する商品はありません
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path,  class:"btn btn-primary btn-lg btn-block mx-5" %>

app/views/items/show.html.erb
<div class="mx-auto" style="width: 530px;">
  <div class="card m-4 border-white " style="width: 30rem;">
    <%= image_tag(@item.image, class:"rounded", width:"478", height:"478") %>
    <div class="card-body border-white">
      <h3 class="card-title mr-3"><strong><%= @item.title %></strong></h3>
        <div class="flex">
          <% if user_signed_in? %>
            <% if current_user.already_liked?(@item) %>
              <%= button_to '「良いね」を取り消す', item_like_path(@item), method: :delete, class:"btn btn-success btn-lg btn-block mr-3" %>
            <% else %>
              <%= button_to '👍', item_likes_path(@item), class:"btn btn-danger btn-lg rounded-circle mr-3" %>
            <% end %>
          <% else %>
            <strong><%= "***「良いね」を押すには、新規登録/ログインが必要です ***"%></strong>
          <% end %>
          <% if user_signed_in? %>
            <h2 class="card-title mt-2 mx-2"><%= @item.likes.count %></h2>
          <% end %>
        </div>
      <p class="card-text"><strong>詳細：</strong><%= @item.explanation %></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong>持ち主：</strong><%= link_to "#{@item.user.nickname}", user_path(current_user) %>さん(<%= @item.region.name %>住み)</li>
      <li class="list-group-item"><strong>種類：</strong><%= @item.genre.name %></li>
    </ul>

    <div class="text-center mt-5">
      <% if  user_signed_in? %>
        <% if current_user.id == @item.user_id %>
          <%= link_to '編集しますか？', edit_item_path(@item.id), class: "btn btn-primary btn-lg btn-block" %>
            <strong><a>or</a></strong>
          <%= link_to '削除しますか？', item_path(@item.id), method: :delete, class:'item-destroy', class: "btn btn-danger btn-lg btn-block" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<div class="text-right m-4">
  <h2><%= @item.comments.count %>件のコメント</h2>
</div>

  <div class="text-right m-4">
    <% if user_signed_in? %>
      <%= form_with(model: [@item, @comment], local: true) do |form| %>
        <%= form.text_area :text, class:"form-control", id:"exampleFormControlTextarea1", placeholder: "コメントを入力", rows: "1" %>
        <h6></h6>
        <div class="text-left"><%= form.submit "コメントする", class:"btn btn-primary btn-lg btn-block" %></div>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>

    <% if @comments.present?%>
      <div class="form-group">
        <% @comments.each do |comment| %>
          <strong><label for="exampleInputEmail1"><%= comment.user.nickname %></label></strong>
          <small id="emailHelp" class="form-text text-muted"><%= comment.created_at %></small>
          <h6><%= comment.text %></h6>
          <p></p>
        <% end %>
      </div>
    <% else %>
      <div class="text-right mt-4">
        <%= "コメントはまだありません。お時間がありましたら、ぜひコメントしましょう！" %>
      </div>
    <% end %>
</div>